// <auto-generated />
using System;
using Aula12_TestandoORM.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aula12_TestandoORM.Migrations
{
    [DbContext(typeof(MeuContexto))]
    [Migration("20230528232528_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Aula12_TestandoORM.Domain.Entities.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstacionamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstacionamentoId");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("Aula12_TestandoORM.Domain.Entities.Estacionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Estacionamentos");
                });

            modelBuilder.Entity("Aula12_TestandoORM.Domain.Entities.Carro", b =>
                {
                    b.HasOne("Aula12_TestandoORM.Domain.Entities.Estacionamento", "Estacionamento")
                        .WithMany("Carro")
                        .HasForeignKey("EstacionamentoId");

                    b.Navigation("Estacionamento");
                });

            modelBuilder.Entity("Aula12_TestandoORM.Domain.Entities.Estacionamento", b =>
                {
                    b.Navigation("Carro");
                });
#pragma warning restore 612, 618
        }
    }
}
